### ISSUE TITLE
Is there reason offset is app 0xBC0 + 0x3C + 0x08? Why not 0xC04?

### ISSUE THREAD

**Issue by groybe** [OpenSimwheel/RBR_FFBTest#1]
Is there reason offset is app 0xBC0 + 0x3C + 0x08? Why not 0xC04?

Thanks.

**Comment by bernhardberger** [comment]
To be honest - I have no clue, not in the slightest. It's been nearly 7 years since I've last seen this code - it may even have been a snippet I found somewhere without questioning it.

Sorry I can't help you - but my best guess is that every one of those 3 mean something and the calculation is written that way for clarity purposes.
